/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.pep.view;

import br.edu.ifsp.pep.control.ControleManutencao;
import br.edu.ifsp.pep.control.ControleVeiculo;
import br.edu.ifsp.pep.model.Manutencao;
import br.edu.ifsp.pep.model.Veiculo;
import java.awt.event.ActionEvent;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.NoResultException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.Conversoes;

/**
 *
 * @author Aluno
 */
public class FormListaManutencoes extends javax.swing.JDialog {

    /**
     * Creates new form FormManuseioVeiculo
     */
    private Veiculo veiculoSelecionado = null;
    
    public void setVeiculo(Veiculo veiculo){
        this.veiculoSelecionado = veiculo;
        txtChassis.setText(veiculoSelecionado.getChassis());
    }
    public FormListaManutencoes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PBackground = new javax.swing.JPanel();
        PMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PExcluir = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PCadastrar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pVoltar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        PAlterar1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tManutencao = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JTextField();
        botPesquisar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botManutencaoPendente = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtChassis = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        PBackground.setBackground(new java.awt.Color(58, 110, 165));
        PBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PMenu.setBackground(new java.awt.Color(51, 51, 51));
        PMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        PMenu.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Administrador");
        PMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        PExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PExcluirMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Excluir");

        javax.swing.GroupLayout PExcluirLayout = new javax.swing.GroupLayout(PExcluir);
        PExcluir.setLayout(PExcluirLayout);
        PExcluirLayout.setHorizontalGroup(
            PExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PExcluirLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel4)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        PExcluirLayout.setVerticalGroup(
            PExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PExcluirLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        PMenu.add(PExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 250, 40));

        PCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PCadastrarMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Cadastrar");

        javax.swing.GroupLayout PCadastrarLayout = new javax.swing.GroupLayout(PCadastrar);
        PCadastrar.setLayout(PCadastrarLayout);
        PCadastrarLayout.setHorizontalGroup(
            PCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCadastrarLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel2)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        PCadastrarLayout.setVerticalGroup(
            PCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        PMenu.add(PCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, 40));

        pVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pVoltarMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Voltar");

        javax.swing.GroupLayout pVoltarLayout = new javax.swing.GroupLayout(pVoltar);
        pVoltar.setLayout(pVoltarLayout);
        pVoltarLayout.setHorizontalGroup(
            pVoltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pVoltarLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(51, 51, 51))
        );
        pVoltarLayout.setVerticalGroup(
            pVoltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        PMenu.add(pVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, -1, 30));

        PAlterar1.setBackground(new java.awt.Color(102, 102, 102));
        PAlterar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PAlterar1MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Alterar");

        javax.swing.GroupLayout PAlterar1Layout = new javax.swing.GroupLayout(PAlterar1);
        PAlterar1.setLayout(PAlterar1Layout);
        PAlterar1Layout.setHorizontalGroup(
            PAlterar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAlterar1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel8)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        PAlterar1Layout.setVerticalGroup(
            PAlterar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAlterar1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        PMenu.add(PAlterar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 250, 40));

        PBackground.add(PMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 720));

        tManutencao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Data", "Tipo", "Chassi", "Valor", "Situação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tManutencao.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tManutencao);

        PBackground.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 770, -1));
        PBackground.add(txtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 230, -1));

        botPesquisar.setBackground(new java.awt.Color(204, 204, 204));
        botPesquisar.setText("Pesquisar");
        botPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botPesquisarMouseClicked(evt);
            }
        });
        PBackground.add(botPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 100, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Tipo:");
        PBackground.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setText("Lista de manutenções");
        PBackground.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        botManutencaoPendente.setText("Pagamento Pendente");
        botManutencaoPendente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botManutencaoPendenteMouseClicked(evt);
            }
        });
        PBackground.add(botManutencaoPendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Numero do Chassis do veículo: ");
        PBackground.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, -1, -1));

        txtChassis.setEditable(false);
        PBackground.add(txtChassis, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 600, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PExcluirMouseClicked
        // TODO add your handling code here:
        int linha = tManutencao.getSelectedRow();
        Integer codigo = 0;
        ControleManutencao controle = new ControleManutencao();
        ControleVeiculo contV = new ControleVeiculo();
        if(linha != -1){
            for(int i=0; i<6; i++){
                System.out.println();
                if(tManutencao.getColumnName(i).equals("Código")){
                    codigo = Integer.parseInt(tManutencao.getValueAt(linha, i).toString());
                }               
            }          
            try{
                Manutencao manu = controle.findByCodigo(codigo, veiculoSelecionado.getChassis());
                if(manu.getStatus().equals("PD")){
                    try {
                        
                        List<Manutencao> lista = veiculoSelecionado.getListaManutencoes();
                        
                        lista.remove(manu);
                        controle.deletar(manu);
                        veiculoSelecionado.setListaManutencoes(lista);
                        contV.alterar(veiculoSelecionado);
                        JOptionPane.showMessageDialog(null, "Manutenção excluída com sucesso!");
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "Erro ao excluir Manutenção!");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Manutenções pagas não podem ser excluidas!");
                }

            }catch(NoResultException ex){
               JOptionPane.showMessageDialog(null, "Erro veiculo não encontrado!"); 
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione uma Manutenção!");
        }
        
        botPesquisarMouseClicked(evt);
    }//GEN-LAST:event_PExcluirMouseClicked

    private void PCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PCadastrarMouseClicked
        // TODO add your handling code here:
        ControleVeiculo cv = new ControleVeiculo();
        
        FormManutencao tela = new FormManutencao(null, true);
        tela.setVeiculo(veiculoSelecionado);
        tela.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_PCadastrarMouseClicked

    private void pVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pVoltarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_pVoltarMouseClicked

    private void PAlterar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAlterar1MouseClicked
        // TODO add your handling code here:
        ControleManutencao controle = new ControleManutencao();
        int linha = tManutencao.getSelectedRow();
        int codigo = 0;
        if(linha != -1){
            for(int i=0; i<6; i++){
                if(tManutencao.getColumnName(i).equals("Código")){
                    codigo = Integer.parseInt(tManutencao.getValueAt(linha, i).toString());
                }               
            }          
        }else{
            JOptionPane.showMessageDialog(null, "selecione uma manutenção!");
            return;
        }
        try{
            FormManutencao tela = new FormManutencao(null, true);
            tela.setVeiculo(veiculoSelecionado);
            tela.setMautencao(controle.findByCodigo(codigo, veiculoSelecionado.getChassis()));
            tela.setVisible(true);
        }catch(NoResultException ex){
            JOptionPane.showMessageDialog(this, "Manutenção não encontrada!");
        }
    }//GEN-LAST:event_PAlterar1MouseClicked

    private void botPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botPesquisarMouseClicked
        // TODO add your handling code here:
        ControleManutencao controle = new ControleManutencao();
        ControleVeiculo cv = new ControleVeiculo();
        List<Manutencao> list = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) tManutencao.getModel();
        try {
            veiculoSelecionado = cv.findByChassis(veiculoSelecionado.getChassis());
            
            model.setNumRows(0);
            list = controle.findByChassis(veiculoSelecionado.getChassis());
            for(Manutencao m: list){
              model.addRow(new Object[] {m.getCodigo(),Conversoes.getDateFormatedToString(m.getDataManutencao()), m.getTipoManutencao(), m.getVeiculo().getPlaca(), m.getValor(), m.getStatus()});
            }
        } catch (NoResultException ex) {
            JOptionPane.showMessageDialog(null, "Veiculo não encontrado!");
        }
    }//GEN-LAST:event_botPesquisarMouseClicked

    private void botManutencaoPendenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botManutencaoPendenteMouseClicked
        // TODO add your handling code here:
        
        ControleManutencao controle = new ControleManutencao();
        ControleVeiculo cv = new ControleVeiculo();
        List<Manutencao> list = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) tManutencao.getModel();
        try {
            veiculoSelecionado = cv.findByChassis(veiculoSelecionado.getChassis());
            
            model.setNumRows(0);
            list = controle.findByCodigoPD(veiculoSelecionado.getChassis());
            for(Manutencao m: list){
              model.addRow(new Object[] {m.getCodigo(),Conversoes.getDateFormatedToString(m.getDataManutencao()), m.getTipoManutencao(), m.getVeiculo().getPlaca(), m.getValor(), m.getStatus()});
            }
        } catch (NoResultException ex) {
            JOptionPane.showMessageDialog(null, "Veiculo não encontrado!");
        }
    }//GEN-LAST:event_botManutencaoPendenteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("skinLF".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormListaManutencoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormListaManutencoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormListaManutencoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormListaManutencoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormListaManutencoes dialog = new FormListaManutencoes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PAlterar1;
    private javax.swing.JPanel PBackground;
    private javax.swing.JPanel PCadastrar;
    private javax.swing.JPanel PExcluir;
    private javax.swing.JPanel PMenu;
    private javax.swing.JButton botManutencaoPendente;
    private javax.swing.JButton botPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pVoltar;
    private javax.swing.JTable tManutencao;
    private javax.swing.JTextField txtChassis;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
