/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.pep.view;

import br.edu.ifsp.pep.control.ControleCliente;
import br.edu.ifsp.pep.control.ControleCrianca;
import br.edu.ifsp.pep.control.ControleLocal;
import br.edu.ifsp.pep.model.Cliente;
import br.edu.ifsp.pep.model.Crianca;
import br.edu.ifsp.pep.model.Local;
import javax.persistence.NoResultException;
import javax.swing.JOptionPane;
import util.Conversoes;

/**
 *
 * @author Aluno
 */
public class LocalForm extends javax.swing.JDialog {

    /**
     * Creates new form CriancaForm
     */
    private Local local = null;
    
    public void setLocal(Local local){
        this.local = local;
        txtIdLocal.setText(String.valueOf(local.getIdLocal()));
        txtIdLocal.setEditable(false);
        txtResponsavel.setText(local.getResponsavel());
        combTipo.setSelectedItem(local.getTipo());
        txtBairro.setText(local.getBairro());
        txtRua.setText(local.getRua());
        txtEmail.setText(local.getEmail());
        txtTelefone.setText(local.getTelefone());
    }
    public LocalForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PBackground = new javax.swing.JPanel();
        PMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PCadastrar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PAlterar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtResponsavel = new javax.swing.JTextField();
        pCancelar = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        pSalvar = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txtIdLocal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        combTipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        PBackground.setBackground(new java.awt.Color(58, 110, 165));
        PBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PMenu.setBackground(new java.awt.Color(51, 51, 51));
        PMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        PMenu.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Administrador");
        PMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Cadastrar");

        javax.swing.GroupLayout PCadastrarLayout = new javax.swing.GroupLayout(PCadastrar);
        PCadastrar.setLayout(PCadastrarLayout);
        PCadastrarLayout.setHorizontalGroup(
            PCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCadastrarLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel2)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        PCadastrarLayout.setVerticalGroup(
            PCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        PMenu.add(PCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, 40));

        PAlterar.setBackground(new java.awt.Color(102, 102, 102));
        PAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PAlterarMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Alterar");

        javax.swing.GroupLayout PAlterarLayout = new javax.swing.GroupLayout(PAlterar);
        PAlterar.setLayout(PAlterarLayout);
        PAlterarLayout.setHorizontalGroup(
            PAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAlterarLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel3)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        PAlterarLayout.setVerticalGroup(
            PAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAlterarLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        PMenu.add(PAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 250, 40));

        PBackground.add(PMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 720));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setText("Cadastro Local");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("id local:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jPanel2.add(txtResponsavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 350, -1));

        pCancelar.setBackground(new java.awt.Color(102, 102, 102));
        pCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pCancelarMouseClicked(evt);
            }
        });
        pCancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel25.setText("Cancelar");
        pCancelar.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 4, -1, 20));

        jPanel2.add(pCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 140, 30));

        pSalvar.setBackground(new java.awt.Color(102, 102, 102));
        pSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pSalvarMouseClicked(evt);
            }
        });
        pSalvar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel24.setText("Cadastrar");
        pSalvar.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 4, -1, 20));

        jPanel2.add(pSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 150, 30));
        jPanel2.add(txtIdLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Telefone:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        combTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Residência", "Escolar" }));
        jPanel2.add(combTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Rua:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));
        jPanel2.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 400, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Bairro:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));
        jPanel2.add(txtRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 400, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Responsável:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 350, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("Email:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        jPanel2.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 150, -1));

        PBackground.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 810, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSalvarMouseClicked
        // TODO add your handling code here:
        ControleLocal controleLocal = new ControleLocal();
        Local local = new Local();
        
        if (txtIdLocal.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo IdLocal!");
            txtIdLocal.requestFocus();
            return;
        }else if(this.local==null){
            try {
                controleLocal.findByIdLocal(Integer.parseInt(txtIdLocal.getText()));
                JOptionPane.showMessageDialog(this, "Local com esse código já existe!");
                return;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Código do local deve ser inteiro!");
                return;
            }catch(NoResultException ex){
                
            }
        }

        if (txtResponsavel.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o campo Nome!");
            txtResponsavel.requestFocus();
            return;
        }
        if (txtBairro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o campo Bairro!");
            txtBairro.requestFocus();
            return;
        }
        if (txtRua.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o campo Rua!");
            txtRua.requestFocus();
            return;
        }
        if (txtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o campo Email!");
            txtEmail.requestFocus();
            return;
        }
        if (txtTelefone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o campo Telefone!");
            txtTelefone.requestFocus();
            return;
        }
        local.setIdLocal(Integer.parseInt(txtIdLocal.getText()));
        local.setTipo(combTipo.getSelectedItem().toString());
        local.setResponsavel(txtResponsavel.getText());
        local.setBairro(txtBairro.getText());
        local.setRua(txtRua.getText());
        local.setEmail(txtEmail.getText());
        local.setTelefone(txtTelefone.getText());

        
        if(this.local == null){
            try {
                controleLocal.inserir(local);
                JOptionPane.showMessageDialog(this, "Local cadastrado com sucesso!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Aconteceu um erro ao cadastrar um local!");
            } 
        }else{
            
            try {
                controleLocal.alterar(local);
                JOptionPane.showMessageDialog(null, "Local alterado com sucesso!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao alterar local!");
            }
        }
        
        this.dispose();
    }//GEN-LAST:event_pSalvarMouseClicked

    private void pCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCancelarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_pCancelarMouseClicked

    private void PAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAlterarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PAlterarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LocalForm dialog = new LocalForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PAlterar;
    private javax.swing.JPanel PBackground;
    private javax.swing.JPanel PCadastrar;
    private javax.swing.JPanel PMenu;
    private javax.swing.JComboBox<String> combTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pCancelar;
    private javax.swing.JPanel pSalvar;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdLocal;
    private javax.swing.JTextField txtResponsavel;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
