/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.pep.view;

import br.edu.ifsp.pep.model.Administrador;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.query.JRJpaQueryExecuterFactory;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import util.Conversoes;

/**
 *
 * @author Aluno
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    Administrador adm = new Administrador();
    
    public void setAdm(Administrador administrador){
        this.adm = administrador;
    }
    
    public Principal() {
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PBackground = new javax.swing.JPanel();
        PMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        pHistoricoUtilizacao = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pCrianca = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pVinculo = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pVeiculos = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pLocal = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pCliente = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        pAdministrador1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        pContrato = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        pMonitor1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pMotorista = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        pRelatorioFuncionario = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pRelatorioGeral = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PBackground.setBackground(new java.awt.Color(58, 110, 165));
        PBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PMenu.setBackground(new java.awt.Color(51, 51, 51));
        PMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        PMenu.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jPanel15.setBackground(new java.awt.Color(255, 0, 0));
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel15MouseClicked(evt);
            }
        });
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel34.setText("Recursos Humanos");
        jPanel15.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jLabel36.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel36.setText("Sair");
        jPanel15.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 50, -1));

        PMenu.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 148, 38));

        PBackground.add(PMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 720));

        pHistoricoUtilizacao.setBackground(new java.awt.Color(204, 204, 204));
        pHistoricoUtilizacao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pHistoricoUtilizacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pHistoricoUtilizacaoMouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Recursos Humanos");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Historico utilização");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_report_card_48px.png"))); // NOI18N

        javax.swing.GroupLayout pHistoricoUtilizacaoLayout = new javax.swing.GroupLayout(pHistoricoUtilizacao);
        pHistoricoUtilizacao.setLayout(pHistoricoUtilizacaoLayout);
        pHistoricoUtilizacaoLayout.setHorizontalGroup(
            pHistoricoUtilizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHistoricoUtilizacaoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel10)
                .addContainerGap(50, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pHistoricoUtilizacaoLayout.setVerticalGroup(
            pHistoricoUtilizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pHistoricoUtilizacaoLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PBackground.add(pHistoricoUtilizacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, 150, 120));

        pCrianca.setBackground(new java.awt.Color(204, 204, 204));
        pCrianca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pCrianca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pCriancaMouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Recursos Humanos");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel12.setText("Criança");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_children_48px.png"))); // NOI18N

        javax.swing.GroupLayout pCriancaLayout = new javax.swing.GroupLayout(pCrianca);
        pCrianca.setLayout(pCriancaLayout);
        pCriancaLayout.setHorizontalGroup(
            pCriancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCriancaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel13)
                .addContainerGap(50, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pCriancaLayout.setVerticalGroup(
            pCriancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCriancaLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PBackground.add(pCrianca, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 150, 120));

        pVinculo.setBackground(new java.awt.Color(204, 204, 204));
        pVinculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pVinculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pVinculoMouseClicked(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Recursos Humanos");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel14.setText("Motorista Monitor");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_add_user_group_man_man_48px.png"))); // NOI18N

        javax.swing.GroupLayout pVinculoLayout = new javax.swing.GroupLayout(pVinculo);
        pVinculo.setLayout(pVinculoLayout);
        pVinculoLayout.setHorizontalGroup(
            pVinculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pVinculoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel15)
                .addContainerGap(50, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pVinculoLayout.setVerticalGroup(
            pVinculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pVinculoLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PBackground.add(pVinculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 150, 120));

        pVeiculos.setBackground(new java.awt.Color(204, 204, 204));
        pVeiculos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pVeiculosMouseClicked(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel17.setText("Veículos");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_van_48px.png"))); // NOI18N

        javax.swing.GroupLayout pVeiculosLayout = new javax.swing.GroupLayout(pVeiculos);
        pVeiculos.setLayout(pVeiculosLayout);
        pVeiculosLayout.setHorizontalGroup(
            pVeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pVeiculosLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        pVeiculosLayout.setVerticalGroup(
            pVeiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pVeiculosLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PBackground.add(pVeiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 150, 120));

        pLocal.setBackground(new java.awt.Color(204, 204, 204));
        pLocal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pLocal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pLocalMouseClicked(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel20.setText("Local");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 50, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_alps_48px.png"))); // NOI18N

        javax.swing.GroupLayout pLocalLayout = new javax.swing.GroupLayout(pLocal);
        pLocal.setLayout(pLocalLayout);
        pLocalLayout.setHorizontalGroup(
            pLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
            .addGroup(pLocalLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pLocalLayout.setVerticalGroup(
            pLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLocalLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PBackground.add(pLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 350, 150, 120));

        pCliente.setBackground(new java.awt.Color(204, 204, 204));
        pCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pClienteMouseClicked(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setText("Recursos Humanos");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel23.setText("Cliente");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_user_male_skin_type_6_48px.png"))); // NOI18N

        javax.swing.GroupLayout pClienteLayout = new javax.swing.GroupLayout(pCliente);
        pCliente.setLayout(pClienteLayout);
        pClienteLayout.setHorizontalGroup(
            pClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pClienteLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel24)
                .addContainerGap(50, Short.MAX_VALUE))
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pClienteLayout.setVerticalGroup(
            pClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pClienteLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PBackground.add(pCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 150, 120));

        pAdministrador1.setBackground(new java.awt.Color(204, 204, 204));
        pAdministrador1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pAdministrador1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pAdministrador1MouseClicked(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel25.setText("Recursos Humanos");
        jPanel9.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jLabel26.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel26.setText("Administrador");
        jPanel9.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_admin_settings_male_48px.png"))); // NOI18N

        javax.swing.GroupLayout pAdministrador1Layout = new javax.swing.GroupLayout(pAdministrador1);
        pAdministrador1.setLayout(pAdministrador1Layout);
        pAdministrador1Layout.setHorizontalGroup(
            pAdministrador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAdministrador1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel27)
                .addContainerGap(50, Short.MAX_VALUE))
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pAdministrador1Layout.setVerticalGroup(
            pAdministrador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAdministrador1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PBackground.add(pAdministrador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 150, 120));

        pContrato.setBackground(new java.awt.Color(204, 204, 204));
        pContrato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pContrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pContratoMouseClicked(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel28.setText("Recursos Humanos");
        jPanel10.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jLabel29.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel29.setText("Contrato");
        jPanel10.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_handshake_48px.png"))); // NOI18N

        javax.swing.GroupLayout pContratoLayout = new javax.swing.GroupLayout(pContrato);
        pContrato.setLayout(pContratoLayout);
        pContratoLayout.setHorizontalGroup(
            pContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContratoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel30)
                .addContainerGap(50, Short.MAX_VALUE))
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pContratoLayout.setVerticalGroup(
            pContratoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pContratoLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PBackground.add(pContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 150, 120));

        pMonitor1.setBackground(new java.awt.Color(204, 204, 204));
        pMonitor1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pMonitor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pMonitor1MouseClicked(evt);
            }
        });

        jPanel11.setBackground(new java.awt.Color(153, 153, 153));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel21.setText("Monitor");
        jPanel11.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_user_female_48px.png"))); // NOI18N

        javax.swing.GroupLayout pMonitor1Layout = new javax.swing.GroupLayout(pMonitor1);
        pMonitor1.setLayout(pMonitor1Layout);
        pMonitor1Layout.setHorizontalGroup(
            pMonitor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
            .addGroup(pMonitor1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pMonitor1Layout.setVerticalGroup(
            pMonitor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMonitor1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PBackground.add(pMonitor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 150, 120));

        pMotorista.setBackground(new java.awt.Color(204, 204, 204));
        pMotorista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pMotorista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pMotoristaMouseClicked(evt);
            }
        });

        jPanel12.setBackground(new java.awt.Color(153, 153, 153));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel31.setText("Recursos Humanos");
        jPanel12.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jLabel32.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel32.setText("Motorista");
        jPanel12.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_driver_48px.png"))); // NOI18N

        javax.swing.GroupLayout pMotoristaLayout = new javax.swing.GroupLayout(pMotorista);
        pMotorista.setLayout(pMotoristaLayout);
        pMotoristaLayout.setHorizontalGroup(
            pMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMotoristaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel33)
                .addContainerGap(50, Short.MAX_VALUE))
            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pMotoristaLayout.setVerticalGroup(
            pMotoristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMotoristaLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PBackground.add(pMotorista, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 150, 120));

        pRelatorioFuncionario.setBackground(new java.awt.Color(204, 204, 204));
        pRelatorioFuncionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pRelatorioFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pRelatorioFuncionarioMouseClicked(evt);
            }
        });

        jPanel13.setBackground(new java.awt.Color(153, 153, 153));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Relatório");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel13.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 20));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setText("de Funcionários");
        jPanel13.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 20, 130, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/newspaper.png"))); // NOI18N

        javax.swing.GroupLayout pRelatorioFuncionarioLayout = new javax.swing.GroupLayout(pRelatorioFuncionario);
        pRelatorioFuncionario.setLayout(pRelatorioFuncionarioLayout);
        pRelatorioFuncionarioLayout.setHorizontalGroup(
            pRelatorioFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pRelatorioFuncionarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(56, 56, 56))
        );
        pRelatorioFuncionarioLayout.setVerticalGroup(
            pRelatorioFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pRelatorioFuncionarioLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PBackground.add(pRelatorioFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, 150, 120));

        pRelatorioGeral.setBackground(new java.awt.Color(204, 204, 204));
        pRelatorioGeral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pRelatorioGeral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pRelatorioGeralMouseClicked(evt);
            }
        });

        jPanel14.setBackground(new java.awt.Color(153, 153, 153));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel19.setText("Relatório Geral");
        jPanel14.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/newspaper.png"))); // NOI18N

        javax.swing.GroupLayout pRelatorioGeralLayout = new javax.swing.GroupLayout(pRelatorioGeral);
        pRelatorioGeral.setLayout(pRelatorioGeralLayout);
        pRelatorioGeralLayout.setHorizontalGroup(
            pRelatorioGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
            .addGroup(pRelatorioGeralLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pRelatorioGeralLayout.setVerticalGroup(
            pRelatorioGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRelatorioGeralLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PBackground.add(pRelatorioGeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, 150, 120));

        getContentPane().add(PBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pHistoricoUtilizacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHistoricoUtilizacaoMouseClicked
        // TODO add your handling code here:
        FormHistoricoUtilizacao tela = new FormHistoricoUtilizacao(this, true);
        tela.setVisible(true);    
    }//GEN-LAST:event_pHistoricoUtilizacaoMouseClicked

    private void pCriancaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCriancaMouseClicked
        // TODO add your handling code here:
        RecursosHumanosCrianca tela = new RecursosHumanosCrianca(this, true);
        tela.setVisible(true);
    }//GEN-LAST:event_pCriancaMouseClicked

    private void pVinculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pVinculoMouseClicked
        // TODO add your handling code here:
        VinculaMotoristaMonitor tela = new VinculaMotoristaMonitor(this, true);
        tela.setVisible(true);
    }//GEN-LAST:event_pVinculoMouseClicked

    private void pVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pVeiculosMouseClicked

        FormManuseioVeiculo tela = new FormManuseioVeiculo(this, true);
        tela.setVisible(true);
    }//GEN-LAST:event_pVeiculosMouseClicked

    private void pLocalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pLocalMouseClicked
        // TODO add your handling code here:
        FormManuseioLocal tela = new FormManuseioLocal(this, true);
        tela.setVisible(true);
    }//GEN-LAST:event_pLocalMouseClicked

    private void pClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pClienteMouseClicked
        // TODO add your handling code here:
        RecursosHumanosCliente tela = new RecursosHumanosCliente(this, true);
        tela.setVisible(true);
    }//GEN-LAST:event_pClienteMouseClicked

    private void pAdministrador1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pAdministrador1MouseClicked
        // TODO add your handling code here:
        RecursosHumanosAdministrador tela = new RecursosHumanosAdministrador(this, true);
        tela.setAdministrador(this.adm);
        tela.setVisible(true);
    }//GEN-LAST:event_pAdministrador1MouseClicked

    private void pContratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pContratoMouseClicked
        // TODO add your handling code here:
        FormManuseioContrato tela = new FormManuseioContrato(this, true);
        tela.setVisible(true);
    }//GEN-LAST:event_pContratoMouseClicked

    private void pMonitor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMonitor1MouseClicked
        // TODO add your handling code here:
        RecursosHumanosMonitor tela = new RecursosHumanosMonitor(this, true);
        tela.setVisible(true);
    }//GEN-LAST:event_pMonitor1MouseClicked

    private void pMotoristaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMotoristaMouseClicked
        // TODO add your handling code here:
        RecursosHumanosMotorista tela = new RecursosHumanosMotorista(this, true);
        tela.setVisible(true);
    }//GEN-LAST:event_pMotoristaMouseClicked

    private void pRelatorioFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pRelatorioFuncionarioMouseClicked
        // TODO add your handling code here:
        EntityManager em = Persistence.createEntityManagerFactory("ProjetoIntegradoPU").createEntityManager();

        try {
            JasperDesign jd = JRXmlLoader
              .load(getClass()
              .getResourceAsStream("/br/edu/ifsp/pep/report/Funcionario.jrxml"));

            JasperReport relatorioCompilado
                    = JasperCompileManager
                            .compileReport(jd);
            HashMap<String, Object> parametros = new HashMap<>();
            parametros.put(JRJpaQueryExecuterFactory.PARAMETER_JPA_ENTITY_MANAGER,em);


            BufferedImage bi = null;
            try {
                bi = ImageIO.read(getClass().getResource("/br/edu/ifsp/pep/report/logo.PNG"));
            } catch (IOException ex) {
                System.out.println("Erro ao carregar imagem.");
            }

            parametros.put("logo", bi);

            JasperPrint jp = JasperFillManager.fillReport(relatorioCompilado, parametros);

            JasperViewer viewer = new JasperViewer(jp, false);
            viewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pRelatorioFuncionarioMouseClicked

    private void pRelatorioGeralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pRelatorioGeralMouseClicked
        // TODO add your handling code here:
        EntityManager em = Persistence.createEntityManagerFactory("ProjetoIntegradoPU").createEntityManager();

        try {
            JasperDesign jd = JRXmlLoader
              .load(getClass()
              .getResourceAsStream("/br/edu/ifsp/pep/report/Geral.jrxml"));

            JasperReport relatorioCompilado
                    = JasperCompileManager
                            .compileReport(jd);
            HashMap<String, Object> parametros = new HashMap<>();
            parametros.put(JRJpaQueryExecuterFactory.PARAMETER_JPA_ENTITY_MANAGER,em);

            Date data = new Date();

            Calendar calen = Calendar.getInstance();
            Calendar calen2 = Calendar.getInstance();
            calen2.set(calen2.get(Calendar.YEAR),calen2.get(Calendar.MONTH), 01);

            
            parametros.put("dataInicio", Conversoes.getDateOfString(Conversoes.getDateFormatedToString(calen2.getTime())));
            parametros.put("dataFim", Conversoes.getDateOfString(Conversoes.getDateFormatedToString(calen.getTime())));

            BufferedImage bi = null;
            try {
                bi = ImageIO.read(getClass().getResource("/br/edu/ifsp/pep/report/logo.PNG"));
            } catch (IOException ex) {
                System.out.println("Erro ao carregar imagem.");
            }

            parametros.put("logo", bi);

            JasperPrint jp = JasperFillManager.fillReport(relatorioCompilado, parametros);

            JasperViewer viewer = new JasperViewer(jp, false);
            viewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pRelatorioGeralMouseClicked

    private void jPanel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseClicked
        // TODO add your handling code here:
        Login tela = new Login();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("skinLF".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PBackground;
    private javax.swing.JPanel PMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel pAdministrador1;
    private javax.swing.JPanel pCliente;
    private javax.swing.JPanel pContrato;
    private javax.swing.JPanel pCrianca;
    private javax.swing.JPanel pHistoricoUtilizacao;
    private javax.swing.JPanel pLocal;
    private javax.swing.JPanel pMonitor1;
    private javax.swing.JPanel pMotorista;
    private javax.swing.JPanel pRelatorioFuncionario;
    private javax.swing.JPanel pRelatorioGeral;
    private javax.swing.JPanel pVeiculos;
    private javax.swing.JPanel pVinculo;
    // End of variables declaration//GEN-END:variables
}
