/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsp.pep.view;

import br.edu.ifsp.pep.control.ControleAdministrador;
import br.edu.ifsp.pep.model.Administrador;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class RecursosHumanosAdministrador extends javax.swing.JDialog {

    /**
     * Creates new form ViewRecursosHumanosAdministrador
     */
    private Administrador admSelecionado = null;
    
    private Administrador ancora = new Administrador();
    public void setAdministrador(Administrador adm){
        this.ancora = adm;
    }
    public RecursosHumanosAdministrador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PBackground = new javax.swing.JPanel();
        PMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PExcluir = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PCadastrar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PAlterar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pVoltar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        PPagarFuncionarios = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAdministrador = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JTextField();
        botPesquisar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        PBackground.setBackground(new java.awt.Color(58, 110, 165));
        PBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PMenu.setBackground(new java.awt.Color(51, 51, 51));
        PMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        PMenu.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Administrador");
        PMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        PExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PExcluirMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Excluir");

        javax.swing.GroupLayout PExcluirLayout = new javax.swing.GroupLayout(PExcluir);
        PExcluir.setLayout(PExcluirLayout);
        PExcluirLayout.setHorizontalGroup(
            PExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PExcluirLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel4)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        PExcluirLayout.setVerticalGroup(
            PExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PExcluirLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        PMenu.add(PExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 250, 40));

        PCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PCadastrarMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Cadastrar");

        javax.swing.GroupLayout PCadastrarLayout = new javax.swing.GroupLayout(PCadastrar);
        PCadastrar.setLayout(PCadastrarLayout);
        PCadastrarLayout.setHorizontalGroup(
            PCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCadastrarLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel2)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        PCadastrarLayout.setVerticalGroup(
            PCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        PMenu.add(PCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, 40));

        PAlterar.setBackground(new java.awt.Color(102, 102, 102));
        PAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PAlterarMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Alterar");

        javax.swing.GroupLayout PAlterarLayout = new javax.swing.GroupLayout(PAlterar);
        PAlterar.setLayout(PAlterarLayout);
        PAlterarLayout.setHorizontalGroup(
            PAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAlterarLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel3)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        PAlterarLayout.setVerticalGroup(
            PAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PAlterarLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        PMenu.add(PAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 250, 40));

        pVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pVoltarMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Voltar");

        javax.swing.GroupLayout pVoltarLayout = new javax.swing.GroupLayout(pVoltar);
        pVoltar.setLayout(pVoltarLayout);
        pVoltarLayout.setHorizontalGroup(
            pVoltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pVoltarLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(51, 51, 51))
        );
        pVoltarLayout.setVerticalGroup(
            pVoltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        PMenu.add(pVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, -1, 30));

        PPagarFuncionarios.setBackground(new java.awt.Color(102, 102, 102));
        PPagarFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PPagarFuncionariosMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Pagamento de Funcionários");

        javax.swing.GroupLayout PPagarFuncionariosLayout = new javax.swing.GroupLayout(PPagarFuncionarios);
        PPagarFuncionarios.setLayout(PPagarFuncionariosLayout);
        PPagarFuncionariosLayout.setHorizontalGroup(
            PPagarFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PPagarFuncionariosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        PPagarFuncionariosLayout.setVerticalGroup(
            PPagarFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PPagarFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        PMenu.add(PPagarFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 250, -1));

        PBackground.add(PMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 720));

        tAdministrador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° Registro", "Nome", "Sexo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tAdministrador.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tAdministrador);

        PBackground.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 580, -1));
        PBackground.add(txtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 230, -1));

        botPesquisar.setBackground(new java.awt.Color(204, 204, 204));
        botPesquisar.setText("Pesquisar");
        botPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botPesquisarMouseClicked(evt);
            }
        });
        PBackground.add(botPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, 90, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Nome:");
        PBackground.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PAlterarMouseClicked
        int linha = tAdministrador.getSelectedRow();
        
        if(linha != -1){        
            ControleAdministrador controle = new ControleAdministrador();
            String numregistro = tAdministrador.getValueAt(0, linha).toString();
            admSelecionado = controle.findByNumRegistro(numregistro);
            AdministradorForm tela = new AdministradorForm(null,true);
            tela.setAdministrador(admSelecionado);
            tela.setVisible(true);
            //this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "selecione um administrador!");
        }
    }//GEN-LAST:event_PAlterarMouseClicked

    private void PExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PExcluirMouseClicked
        // TODO add your handling code here:
        int linha = tAdministrador.getSelectedRow();
        if(linha != -1){
            String numeroRegistro = tAdministrador.getValueAt(0, linha).toString();
            ControleAdministrador controle = new ControleAdministrador();        
            Administrador a = controle.findByNumRegistro(numeroRegistro);
            if(a.getNumeroRegistro().equals(this.ancora.getNumeroRegistro())){
                JOptionPane.showMessageDialog(null, "Você não pode excluir a si mesmo!");
                return;
            }else{
                a.setStatus(false);
                try {
                    controle.alterar(a);
                    JOptionPane.showMessageDialog(null, "Administrador excluído com sucesso!");
                    botPesquisarMouseClicked(evt);
                } catch (Exception ex) {
                    Logger.getLogger(RecursosHumanosMotorista.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Erro ao excluir o administrador!");
                }     
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione um administrador");
        }
    }//GEN-LAST:event_PExcluirMouseClicked

    private void PCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PCadastrarMouseClicked
        // TODO add your handling code here:
        AdministradorForm tela = new AdministradorForm(null, true);
        tela.setVisible(true);
        //this.dispose();
        botPesquisarMouseClicked(evt);
    }//GEN-LAST:event_PCadastrarMouseClicked

    private void pVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pVoltarMouseClicked
        // TODO add your handling code here:
        //RecursosHumanos tela = new RecursosHumanos(null, false);
        //tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pVoltarMouseClicked

    private void botPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botPesquisarMouseClicked
        // TODO add your handling code here:
        ControleAdministrador controle = new ControleAdministrador();
        List<Administrador> list = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) tAdministrador.getModel();
        model.setNumRows(0);
        list = controle.findByNome(txtPesquisar.getText());
        for(Administrador a: list){
            model.addRow(new Object[] {a.getNumeroRegistro(), a.getNomeFuncionario(), a.getSexo()});
        }       
    }//GEN-LAST:event_botPesquisarMouseClicked

    private void PPagarFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PPagarFuncionariosMouseClicked
        // TODO add your handling code here:
        PagamentoFuncionario tela = new PagamentoFuncionario(null, true);
        tela.setVisible(true);
    }//GEN-LAST:event_PPagarFuncionariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecursosHumanosAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecursosHumanosAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecursosHumanosAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecursosHumanosAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RecursosHumanosAdministrador dialog = new RecursosHumanosAdministrador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PAlterar;
    private javax.swing.JPanel PBackground;
    private javax.swing.JPanel PCadastrar;
    private javax.swing.JPanel PExcluir;
    private javax.swing.JPanel PMenu;
    private javax.swing.JPanel PPagarFuncionarios;
    private javax.swing.JButton botPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pVoltar;
    private javax.swing.JTable tAdministrador;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
